name: Install Napi-Postinstall on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your desired Node version

      - name: Install build tools (if needed)
        run: |
          npm install --global --production windows-build-tools

      - name: Install napi-postinstall
        run: npm install napi-postinstall@0.3.1
