name: Advanced Postinstall Simulation

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup InvisiRisk - Build Application Firewall
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_WIN_STAGE }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (triggers postinstall)
        env:
          SAFE_SIM: "true"
        run: npm install

      - name: Verify simulation
        run: dir

      - name: Cleanup Build Application Firewall
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"

  gather_analytics:
    runs-on: ubuntu-latest
    name: Gather Analytics
    needs: [build]
    steps:
      - name: Gather Status
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{ secrets.IR_API_KEY_WIN_STAGE }}
          send_job_status: "true"
